[from.block]
rule_classes = ['regex:^javadoc_', 'regex:_import$', 'regex:^py_']

[[from.filters]]
type = "FunctionCall"
func = "select"
keys = ["deps"]

[[from.filters]]
type = "FunctionCall"
func = "select"
keys = ["defines"]
transitive = true

[to.block]
rule_classes = ['regex:_import$']
