[[from.filters]]
type = "Rule"
block.rule_classes = ['regex:^javadoc_', 'regex:_import$', 'regex:^py_']

[[from.filters]]
type = "FunctionCall"
func = "select"
keys = ["deps", "defines"]

[[from.filters]]
type = "Alias"

[[to.filters]]
type = "Rule"
block.rule_classes = ['regex:_import$']

[[to.filters]]
type = "FunctionCall"
func = "select"
keys = ["deps", "defines"]
