[from.block]
rule_classes = ['regex:^javadoc_', 'regex:_import$', 'regex:^py_']

[from.filters]
func_filter = {func = "select", keys = ["deps", "defines"]}

[to.block]
rule_classes = ['regex:_import$']

[to.filters]
func_filter = {func = "select", keys = ["deps", "defines"]}
