load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "Main",
    srcs = ["src/com/example/Main.java"],
    deps = [
        "//src/com/example/liba",
        "//src/com/example/libb",
    ],
)
