rust_library(
  name = "libb",
  srcs = ["libb.rs"],
  deps = ["//liba:liba"],
  visibility = ["PUBLIC"]
)

rust_library(
  name = "libc",
  srcs = ["libc.rs"],
  deps = [":libb"],
  visibility = ["PUBLIC"]
)
