load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "core_cxx",
    srcs = ["core.cc"],
    hdrs = ["core.h"],
    includes = ["."],
    visibility = ["//visibility:public"],
)
