load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "libd",
    srcs = ["ClassD.kt"],
    visibility = ["//visibility:public"],
    deps = [
        "//liba",
        "//libb",
        "//libc",
    ],
)
